/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Utilitarios.ModeloTabela;
import Utilitarios.conectaBanco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Italo O
 */
public class FechamentoDeCaixa extends javax.swing.JFrame {
    
    conectaBanco conecta= new conectaBanco();
    SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MM-yyyy");
    ArrayList dadosDoDia=new ArrayList(),dadosDiario=new ArrayList();
    String[] ColunasDoDia=new String[]{"Ordem","Nome","Especialidade","Dia","Valor"};
    String[] ColunasDiario=new String[]{"Ordem","Dia","Valor"};
    double ValorDoDia=0,ValorDaSemana=0;

    public FechamentoDeCaixa() {
        initComponents();
        conecta.conexao();
        preencherTabelaFolhaDePagamentoDoDia();
        preencherTabelaFolhaDePagamentoDiario();
        preencherTabelaFolhaDePagamentoMensalEAnual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEspecialidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFolhaDePagamentoDoDia = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDiario = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSemanalAnual = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSpinnerReais = new javax.swing.JSpinner();
        jSpinnerCentavos = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTotalDoDia = new javax.swing.JTextField();
        jTextFieldOrdem = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jButtonFinalizarDia = new javax.swing.JButton();
        jDateChooserPrimeiraDataSemana = new com.toedter.calendar.JDateChooser();
        jDateChooserSegundaDataSemana = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonFinalizarSemana = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FECHAMENTO DE CAIXA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Especialidade:");

        jTextFieldEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEspecialidadeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data:");

        jButtonConfirmar.setText("CONFIRMAR");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jTableFolhaDePagamentoDoDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFolhaDePagamentoDoDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFolhaDePagamentoDoDiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableFolhaDePagamentoDoDiaMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTableFolhaDePagamentoDoDia);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fluxo de caixa:");

        jTableDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableDiario);

        jTabbedPane2.addTab("DIÁRIO", jScrollPane3);

        jTableSemanalAnual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableSemanalAnual);

        jTabbedPane2.addTab("SEMANAL/ANUAL", jScrollPane4);

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total:");

        jTextFieldTotalDoDia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTotalDoDia.setEnabled(false);

        jTextFieldOrdem.setEnabled(false);
        jTextFieldOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrdemActionPerformed(evt);
            }
        });

        jTextFieldValor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldValor.setEnabled(false);

        jButtonFinalizarDia.setText("FINALIZAR DIA");
        jButtonFinalizarDia.setEnabled(false);
        jButtonFinalizarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarDiaActionPerformed(evt);
            }
        });

        jDateChooserPrimeiraDataSemana.setDateFormatString("dd-MM-yyyy");

        jDateChooserSegundaDataSemana.setDateFormatString("dd-MM-yyyy");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("1º dia da semana:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Último dia da semana:");

        jButtonFinalizarSemana.setText("FINALIZAR SEMANA");
        jButtonFinalizarSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarSemanaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAIO", "JUNHO", "JULHO" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Mês:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButtonEditar.setText("EDITAR");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome)
                            .addComponent(jTextFieldEspecialidade)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldValor)
                                    .addComponent(jTextFieldTotalDoDia, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinnerReais)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextFieldOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserPrimeiraDataSemana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserSegundaDataSemana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFinalizarSemana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFinalizarDia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirmar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerReais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTotalDoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserSegundaDataSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserPrimeiraDataSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFinalizarDia)
                        .addComponent(jButtonFinalizarSemana))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEspecialidadeActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
       if(!jTextFieldNome.getText().isEmpty()&&!jTextFieldEspecialidade.getText().isEmpty()
                &&jDateChooser1.getDate()!=null){
            try {
            //cadastrar na tabela de alunos
            PreparedStatement pst=conecta.conn.prepareStatement("insert into FolhaDePagamentoDoDia(NOME,ESPECIALIDADE,DIA,VALOR) "
                    + "Values(?,?,?,?)");
            pst.setString(1,jTextFieldNome.getText());
            pst.setString(2,jTextFieldEspecialidade.getText());
            pst.setString(3, DateFormat.format(jDateChooser1.getDate()));
            pst.setString(4, jSpinnerReais.getValue().toString()+"."+jSpinnerCentavos.getValue().toString());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Pagamento cadastrado com sucesso!");
            EsvaziarCamposDeTexto();
            preencherTabelaFolhaDePagamentoDoDia();
            } catch (NullPointerException | SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro na inserção!\n Erro:"+ex);    
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos obrigatorios!");
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jTableFolhaDePagamentoDoDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFolhaDePagamentoDoDiaMouseClicked
        // TODO add your handling code here:
        ModeloTabela ModeloTabela=new ModeloTabela(dadosDoDia,ColunasDoDia);
        jTableFolhaDePagamentoDoDia.getModel();
        int index = jTableFolhaDePagamentoDoDia.getSelectedRow();
        java.util.Date Dia=null;
                
        String Ordem=""+jTableFolhaDePagamentoDoDia.getValueAt(jTableFolhaDePagamentoDoDia.getSelectedRow(), 0);
        jTextFieldOrdem.setText(Ordem);
        String Nome=""+jTableFolhaDePagamentoDoDia.getValueAt(jTableFolhaDePagamentoDoDia.getSelectedRow(), 1);
        jTextFieldNome.setText(Nome);
        String Especialidade=""+jTableFolhaDePagamentoDoDia.getValueAt(jTableFolhaDePagamentoDoDia.getSelectedRow(), 2);
        jTextFieldEspecialidade.setText(Especialidade);
        String Valor=""+jTableFolhaDePagamentoDoDia.getValueAt(jTableFolhaDePagamentoDoDia.getSelectedRow(), 4);
        jTextFieldValor.setText(Valor);
        try {
            Dia = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTableFolhaDePagamentoDoDia.getValueAt(index, 3));
        } catch (NullPointerException ex) {
            System.out.println("oi");
        } catch (ParseException ex) {
            Logger.getLogger(FechamentoDeCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDateChooser1.setDate(Dia);
        fazerSomaValorDoDia();
        jButtonFinalizarDia.setEnabled(true);
        jButtonConfirmar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableFolhaDePagamentoDoDiaMouseClicked

    private void jTextFieldOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrdemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrdemActionPerformed

    private void jButtonFinalizarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarDiaActionPerformed
        // TODO add your handling code here:
        try {
            //cadastrar na tabela de alunos
            PreparedStatement pst=conecta.conn.prepareStatement("insert into FolhaDePagamentoDiario(DIA,VALOR) "
                    + "Values(?,?)");
            pst.setString(1, DateFormat.format(jDateChooser1.getDate()));
            pst.setString(2,jTextFieldTotalDoDia.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Fechamento de caixa do dia realizado com sucesso!");
            EsvaziarCamposDeTexto();
            preencherTabelaFolhaDePagamentoDiario();
            } catch (NullPointerException | SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro na inserção!\n Erro:"+ex);    
            }
    }//GEN-LAST:event_jButtonFinalizarDiaActionPerformed

    private void jButtonFinalizarSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarSemanaActionPerformed
        // TODO add your handling code here:
        fazerSomaValorDaSemana();
    }//GEN-LAST:event_jButtonFinalizarSemanaActionPerformed

    private void jTableFolhaDePagamentoDoDiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFolhaDePagamentoDoDiaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableFolhaDePagamentoDoDiaMouseEntered

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        conecta.executaSQLExcluir("delete from folhadepagamentododia where ORDEM='"+jTextFieldOrdem.getText()+"'");
        JOptionPane.showMessageDialog(rootPane, "Usuário excluido com sucesso!");
        preencherTabelaFolhaDePagamentoDoDia();
        jTextFieldNome.setText("");
        jTextFieldEspecialidade.setText("");
        jButtonConfirmar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        if((jTextFieldNome.getText().isEmpty())||(jTextFieldEspecialidade.getText().isEmpty())
                ||(jDateChooser1.getDate()==null)){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos obrigatorios!");
        }
        else{    
            try {
            PreparedStatement pst=conecta.conn.prepareStatement("update folhadepagamentododia set NOME=?,ESPECIALIDADE=?,DIA=?,valor=?"
                    + "where ordem=?");
            pst.setString(1,jTextFieldNome.getText());
            pst.setString(2,jTextFieldEspecialidade.getText());
            pst.setString(3, DateFormat.format(jDateChooser1.getDate()));
            pst.setString(4, jSpinnerReais.getValue().toString()+"."+jSpinnerCentavos.getValue().toString());
            pst.setString(5,jTextFieldOrdem.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Dados do pagamento editado com sucesso!");
            preencherTabelaFolhaDePagamentoDoDia();
            jButtonConfirmar.setEnabled(true);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jTextFieldNome.setText("");
            jTextFieldEspecialidade.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Erro ao editar\n Erro:"+ex);
            }   
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed
    public void preencherColunasFolhaDePagamentoDoDia(String SQL){
        ArrayList dadosDoDia=new ArrayList();
        String[] ColunasDoDia=new String[]{"Ordem","Nome","Especialidade","Dia","Valor"};
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do{
            dadosDoDia.add(new Object[]{conecta.rs.getInt("Ordem"),conecta.rs.getString("Nome"),conecta.rs.getString("Especialidade"),
                conecta.rs.getString("Dia"),conecta.rs.getString("Valor")});
            }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a tabela ou tabela vazia (ArrayList)!\n Erro:"+ex);
        }
        ModeloTabela ModeloTabela=new ModeloTabela(dadosDoDia,ColunasDoDia);
        jTableFolhaDePagamentoDoDia.setModel(ModeloTabela);
    }
    public void preencherTabelaFolhaDePagamentoDoDia(){
        preencherColunasFolhaDePagamentoDoDia("select * from folhadepagamentododia");           
    }
    public void preencherColunasFolhaDePagamentoDiario(String SQL){
        ArrayList dadosDiario=new ArrayList();
        String[] ColunasDiario=new String[]{"Ordem","Dia","Valor"};
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do{
            dadosDiario.add(new Object[]{conecta.rs.getInt("ORDEM"),conecta.rs.getString("DIA"),conecta.rs.getString("VALOR")});
            }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a tabela ou tabela vazia (ArrayList)!\n Erro:"+ex);
        }
        ModeloTabela ModeloTabela=new ModeloTabela(dadosDiario,ColunasDiario);
        jTableDiario.setModel(ModeloTabela);
    }
    public void preencherTabelaFolhaDePagamentoDiario(){
        preencherColunasFolhaDePagamentoDiario("select * from folhadepagamentodiario");           
    }
    public void preencherColunasFolhaDePagamentoMensalEAnual(String SQL){
        ArrayList dadosDoDia=new ArrayList();
        String[]  ColunasDoDia=new String[]{"Ordem","ANO","MES","TOTALDOMES","SEMANA1","SEMANA2","SEMANA3","SEMANA4"};
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do{
            dadosDoDia.add(new Object[]{conecta.rs.getInt("Ordem"),conecta.rs.getString("ANO"),conecta.rs.getString("MES"),
                conecta.rs.getString("TOTALDOMES"),conecta.rs.getString("SEMANA1"),conecta.rs.getString("SEMANA1"),
                conecta.rs.getString("SEMANA2"),conecta.rs.getString("SEMANA3"),conecta.rs.getString("SEMANA4")});
            }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a tabela ou tabela vazia (ArrayList)!\n Erro:"+ex);
        }
        ModeloTabela ModeloTabela=new ModeloTabela(dadosDoDia,ColunasDoDia);
        jTableSemanalAnual.setModel(ModeloTabela);
    }
    public void preencherTabelaFolhaDePagamentoMensalEAnual(){
        preencherColunasFolhaDePagamentoMensalEAnual("select * from folhadepagamentosemanalemensal");           
    }
    public void EsvaziarCamposDeTexto(){
       jTextFieldNome.setText("");
       jTextFieldEspecialidade.setText("");
       jDateChooser1.getDate();
    }
    public void fazerSomaValorDoDia(){
        SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MM-yyyy");
        ValorDoDia= conecta.somaSQL("select sum(VALOR)from FolhaDePagamentoDoDia where DIA like'%"+DateFormat.format(jDateChooser1.getDate())+"%'");
        jTextFieldTotalDoDia.setText(String.valueOf(ValorDoDia));
    }
    public void fazerSomaValorDaSemana(){
        SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MM-yyyy");
        ValorDaSemana= conecta.somaSQL("select sum(VALOR)from FolhaDePagamentoDiario where DIA like'%"+DateFormat.format(jDateChooser1.getDate())+"%'");
        jTextField1.setText(String.valueOf(ValorDaSemana));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FechamentoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FechamentoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FechamentoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FechamentoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FechamentoDeCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFinalizarDia;
    private javax.swing.JButton jButtonFinalizarSemana;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooserPrimeiraDataSemana;
    private com.toedter.calendar.JDateChooser jDateChooserSegundaDataSemana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerCentavos;
    private javax.swing.JSpinner jSpinnerReais;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDiario;
    private javax.swing.JTable jTableFolhaDePagamentoDoDia;
    private javax.swing.JTable jTableSemanalAnual;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldEspecialidade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldOrdem;
    private javax.swing.JTextField jTextFieldTotalDoDia;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
